sudo: false
language: go
install: go get -v github.com/spf13/hugo
# before_install:
# - sudo apt-get update
# - sudo apt-get install nodejs
# - sudo apt-get install npm
# before_script:
# - npm install -g gulp
# - npm install
script:
  - hugo
  - hugo version
  # - gulp min-html
