theme = "devopsdays-theme"
baseurl = "https://devopsdayspt.azurewebsites.net/"
# baseurl = "http://localhost:1313/"
languageCode = "en-us"
GoogleAnalytics = "UA-9713393-1"
title = "DevOpsDays"
canonifyurls = false
dataDir = "data"
archetypedir = "archetypes"
PaginatePath = "blog"
buildDrafts = false
disableKinds = ["taxonomy", "taxonomyTerm"]

[[menu.main]]
  name = "events"
  url = "/events"
  weight = -150
[[menu.main]]
  name = "blog"
  url = "/blog"
  weight = -140
[[menu.main]]
  name = "sponsor"
  url = "/sponsor"
  weight = -130
[[menu.main]]
  name = "speaking"
  url = "/speaking"
  weight = -120
[[menu.main]]
  name = "organizing"
  url = "/organizing"
  weight = -110
[[menu.main]]
  name = "about"
  url = "/about"
  weight = -100

[permalinks]
  page = "/:filename/"
  blog = "/blog/:year/:month/:day/:title/"
  speaking = "/:filename/"


[params]
  Facebook = "//www.facebook.com/group.php?gid=106761636771"
  Twitter = "http://www.twitter.com/devopsdays"
  Linkedin = "http://www.linkedin.com/groups?home=&gid=2445279"
  Groups = "http://groups.google.com/group/devopsdays"
