theme = "devopsdays-responsive"
baseurl = "https://www.devopsdays.org/"
# baseurl = "http://localhost:1313/"
languageCode = "en-us"
GoogleAnalytics = "UA-9713393-1"
title = "DevOpsDays"
canonifyurls = false
dataDir = "data"
archetypedir = "archetypes"
PaginatePath = "blog"
buildDrafts = false

[permalinks]
	page = "/:filename/"
  blog = "/blog/:year/:month/:day/:title/"

[params]
	Facebook = "//www.facebook.com/group.php?gid=106761636771"
	Twitter = "http://www.twitter.com/devopsdays"
	Linkedin = "http://www.linkedin.com/groups?home=&gid=2445279"
	Groups = "http://groups.google.com/group/devopsdays"

	# Set to "/" on *nix and Mac, "\\" on Windows
	# Refer to https://github.com/spf13/hugo/issues/2394 for more information
	PathSeperator = "\\"
