# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
 command = "bin/netlify-production.sh"
 publish = "dist/"

 [context.deploy-preview]
  command = "bin/netlify.sh"
  publish = "public/"

[context.production.environment]
   HUGO_VERSION = "0.53"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.53"
