# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
 #command = "bin/netlify.sh"
 #publish = "public/"
 command = "bin/netlify-production.sh"
 publish = "dist/"
 
[context.production.environment]
   HUGO_VERSION = "0.20"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview]
  publish = "public/"
  command = "bin/netlify.sh"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.20"

[context.test]
 command = "bin/netlify-production.sh"
 publish = "dist/"

[context.updates-for-new-theme]
  command = "bin/netlify-production.sh"
  publish = "dist/"
