# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
 command = "bin/netlify-production.sh"
 publish = "public/"

 [context.deploy-preview]
  command = "bin/netlify.sh"
  publish = "public/"
  skip_processing = true

 [context.branch-deploy]
  command = "bin/netlify.sh"
  publish = "public/"
  skip_processing = true
  
#[build.processing]
# skip_processing = true

[context.production.environment]
   HUGO_VERSION = "0.123.3"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.123.3"
  DART_SASS_VERSION = "1.71.1"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.123.3"
  DART_SASS_VERSION = "1.71.1"

# Mastodon Configuration
[[redirects]]
  from = "/.well-known/webfinger/*"
  to = "https://social.devopsdays.org/:splat"
  status = 301
[[headers]]
  for = "/.well-known/webfinger/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    
[[plugins]]
  package = "netlify-plugin-dartsass"