version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.53
    working_directory: ~/devopsdays
    steps:
      - checkout
      - run:
          name: "Run Hugo"
          command: HUGO_ENV=production hugo -v -d workspace/public
      - persist_to_workspace:
          root: workspace
          paths: 
            - public

  test:
    docker:
      - image: circleci/node:4.8.2
    working_directory: ~/devopsdays
    steps:
      - checkout
      - attach_workspace:
          at: ~/devopsdays/workspace
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.4.1'
      - run:
          name: npm-version
          command: 'npm version'
      - run: 
          name: install-gulp
          command: 'sudo npm install -g gulp'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-stuff
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: "List contents"
          command: ls
      - run:
          name: "Test build"
          command: gulp min-html --cwd workspace

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build