# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "devopsdays Theme"
license = "MIT"
licenselink = "https://github.com/devopsdays/devopsdays-theme/blob/master/LICENSE.md"
description = ""
homepage = "https://github.com/devopsdays/devopsdays-theme/"
tags = ["", ""]
features = ["", ""]
min_version = 0.18
theme_version = 1.10.2

[author]
  name = "Matt Stratton"
  homepage = "https://www.mattstratton.io"
